# Site settings
name: Hemanth Raj Tekumalla
title: Hemanth Raj Tekumalla | MS in Robotics @ Northeastern University
description: Robotics Engineer | MS in Robotics @ Northeastern University | Perception 路 SLAM 路 Learning-based Control 路 Path Planning 路 ROS 2
url: https://thraj0103.github.io/
baseurl: ''
email: tekumalla.h@northeastern.edu
cover: /img/H_Icon.png
logo: /img/H_Icon.png
resume: https://thraj0103.github.io/HemanthCV.pdf
social:
  - title: email
    url: mailto:tekumalla.h@northeastern.edu
  # - title: twitter
  #   url: https://twitter.com/bchiang7
  - title: github
    url: https://github.com/thraj0103
  - title: linkedin
    url: https://www.linkedin.com/in/thraj0103/
  - title: instagram
    url: https://instagram.com/thraj0103
  # - title: codepen
  #   url: http://codepen.io/bchiang7


# Build settings
markdown: kramdown

# Sass configuration
sass:
  sass_dir: _scss
  style: compressed

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

# plugins_dir:
#   - jekyll-minifier
#   - jekyll-sitemap

plugins:
  - jekyll-sitemap
